Change namespace to jkirk
Changed the namespace to jkirk as this is what we currently use.
Without that change, running molecule locally is not possible.

Updated ansible-lint with pre-commit autoupdate because it failed with:

  Ansible-lint.............................................................Failed
  - hook id: ansible-lint
  - exit code: 1

  Traceback (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "/home/jkirk/.cache/pre-commit/repodn5kgvlt/py_env-python3/lib/python3.11/site-packages/ansiblelint/__main__.py", line 50, in <module>
      from ansiblelint import cli
    File "/home/jkirk/.cache/pre-commit/repodn5kgvlt/py_env-python3/lib/python3.11/site-packages/ansiblelint/cli.py", line 30, in <module>
      from ansiblelint.yaml_utils import clean_json
    File "/home/jkirk/.cache/pre-commit/repodn5kgvlt/py_env-python3/lib/python3.11/site-packages/ansiblelint/yaml_utils.py", line 34, in <module>
      from ansiblelint.utils import Task
    File "/home/jkirk/.cache/pre-commit/repodn5kgvlt/py_env-python3/lib/python3.11/site-packages/ansiblelint/utils.py", line 45, in <module>
      from ansible.parsing.yaml.constructor import AnsibleConstructor, AnsibleMapping
  ModuleNotFoundError: No module named 'ansible.parsing.yaml.constructor'

Added "language_version: python3.11" because pre-commit failed with:

  An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python3', '-mvirtualenv', '/home/jkirk/.cache/pre-commit/repoll_87xh6/py_env-python3.13', '-p', 'python3.13')
  return code: 1
  stdout:
      RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.13'

Actually only Python3.13 is supported, see:
https://github.com/ansible/ansible-lint/pull/4796 but setting
language_version seems to be good workaround. Got it from here:
https://github.com/ansible/ansible-lint/commit/50007a74500ec16c3e89b53a447cb5e775e3dfd1

This change should also make the Github Workflow Ansible Molecule happy.